seed: 42
run_name: "phase0_spike"

data:
  path: "data/sample.jsonl"
  text_key: "input"
  label_key: "label"
  split: "test"
  max_samples: 10

gen:
  mode: "reverse"           # optional: reverse | echo | uppercase
  template: "Q: {x}\nA:"
  max_tokens: 64

metrics:
  - name: "exact_match"
  - name: "f1_binary"

report:
  out_dir: "outputs"
  save_samples: true
  save_metrics: true
  save_log: true

# Optional: enable to use Hugging Face Lighteval with vLLM backend
lighteval:
  enabled: false
  backend: "vllm"
  # Set your model here or override via CLI: lighteval.model_path=Qwen/Qwen2.5-7B-Instruct
  model_path: null
  # Task string as accepted by Lighteval, e.g., "leaderboard|truthfulqa:mc|0|0"
  tasks: "leaderboard|boolq|0|0"
  # Optional advanced parameters forwarded to Lighteval's model config
  model_parameters: {}
  generation_parameters: {}
